sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t miguel65465/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true miguel65465/docker-react npm run test
